# AUTO-GENERATED by scripts/initialize_aws.sh — do not edit by hand
terraform {
  backend "s3" {
    bucket         = "phantom-link-tfstate"
    key            = "us-east-1/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "phantom-link-tfstate-lock"
    encrypt        = true
  }
}
