#!/bin/bash
# initialize_aws.sh — run ONCE to create remote state infra
#
# What this does:
#   1. Creates S3 bucket for Terraform state
#   2. Blocks all public access
#   3. Enables versioning
#   4. Enables AES-256 encryption at rest
#   5. Creates DynamoDB table for state locking
#   6. Auto-generates infra/envs/us-east-1/backend.tf

set -euo pipefail

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [CONFIG] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
BUCKET_NAME="phantom-link-tfstate"
TABLE_NAME="phantom-link-tfstate-lock"
STATE_KEY="us-east-1/terraform.tfstate"
AWS_REGION="us-east-1"

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_FILE="$SCRIPT_DIR/../infra/envs/us-east-1/backend.tf"

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [PREFLIGHT] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "      Bootstrap State Backend     "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "Account : $ACCOUNT_ID"
echo "Region  : $AWS_REGION"
echo "Bucket  : $BUCKET_NAME"
echo "Table   : $TABLE_NAME"
echo "Key     : $STATE_KEY"
echo ""

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [S3 BUCKET] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
  echo "[SKIP] Bucket already exists: $BUCKET_NAME"
else
  echo "[CREATE] S3 bucket: $BUCKET_NAME"
  aws s3api create-bucket \
    --bucket "$BUCKET_NAME" \
    --region "$AWS_REGION"

  aws s3api put-public-access-block \
    --bucket "$BUCKET_NAME" \
    --public-access-block-configuration \
      "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

  aws s3api put-bucket-versioning \
    --bucket "$BUCKET_NAME" \
    --versioning-configuration Status=Enabled

  aws s3api put-bucket-encryption \
    --bucket "$BUCKET_NAME" \
    --server-side-encryption-configuration '{
      "Rules": [{
        "ApplyServerSideEncryptionByDefault": {
          "SSEAlgorithm": "AES256"
        }
      }]
    }'

  echo "[OK] Bucket configured"
fi

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [DynamoDB LOCK] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
if aws dynamodb describe-table --table-name "$TABLE_NAME" --region "$AWS_REGION" 2>/dev/null; then
  echo "[SKIP] DynamoDB table already exists: $TABLE_NAME"
else
  echo "[CREATE] DynamoDB table: $TABLE_NAME"
  aws dynamodb create-table \
    --table-name "$TABLE_NAME" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$AWS_REGION"

  echo "[OK] DynamoDB table created"
fi

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [GENERATE BACKEND.tf] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
cat > "$BACKEND_FILE" <<EOF
# AUTO-GENERATED by scripts/initialize_aws.sh — do not edit by hand
terraform {
  backend "s3" {
    bucket         = "${BUCKET_NAME}"
    key            = "${STATE_KEY}"
    region         = "${AWS_REGION}"
    dynamodb_table = "${TABLE_NAME}"
    encrypt        = true
  }
}
EOF

echo "[OK] Generated: $BACKEND_FILE"

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [COMPLETE] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
echo ""
echo "(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)"
echo ""
echo " [COMPLETE] State backend is ready"
echo ""
echo " bucket         = \"$BUCKET_NAME\""
echo " key            = \"$STATE_KEY\""
echo " region         = \"$AWS_REGION\""
echo " dynamodb_table = \"$TABLE_NAME\""
echo ""
echo " [NEXT]: cd infra/envs/us-east-1 && terraform init"
echo ""
